### ISSUE TITLE
JI spontaneously stopped working

### ISSUE THREAD

**Issue by FireFliesMC** [ItemMeta/JI#13]
So I started my server up today, and noticed that JI wasn't loaded in the plugins (it's red). This isn't a problem with ProtocolLib and I haven't changed anything.

Here is my console on startup: https://pastebin.com/efU8aED3

**Comment by Ismael-GT** [comment]
They block all the servers using the plugin JI, it doesn't works for any server.

**Comment by ItemMeta** [comment]
It's fixed.
