### ISSUE TITLE
JI Bypass

### ISSUE THREAD

**Issue by challoners-site** [ItemMeta/JI#2]
Flux Client Build 4, AirJump Bypasses and sets of 0 alerts.

**Comment by BenjaminZehowlt** [comment]
Please provide a video, and provide a client link if possible

**Comment by challoners-site** [comment]
Edit // Sets off a few alerts but only after loads of trying
2nd Edit // Flux bypasses mostly all checks, video coming soon

**Comment by challoners-site** [comment]
Client: https://www.youtube.com/watch?v=LUHjhy3gsGI
Video: https://youtu.be/BXEg_h_VMDU

**Comment by BenjaminZehowlt** [comment]
Kill Aura only checks if it is another player
Fly / AirJump is getting a new check
Speed / Hop is being worked on

**Comment by challoners-site** [comment]
Okay thanks

**Comment by BenjaminZehowlt** [comment]
Just Tested Flux b4 Speed on Hop mode it does not bypass
