### ISSUE TITLE
Problem HitAccuracy

### ISSUE THREAD

**Issue by Ismael-GT** [ItemMeta/JI#4]
Hello,

There is a simple bug in this option, if I change max-vl: 1 to 2 HitAccuracy in the config, always is one and never has alerts and directly go to ban-timer and then punish-command.

I think is not neccesary give images only test, I have the last version 3.0.1

**Comment by BenjaminZehowlt** [comment]
Yes, this check was coded by someone else which just instantly calls Autoban code this should be fixed in the next update.

**Comment by Ismael-GT** [comment]
I hope an update soon, I consider the error I told you earlier it's important.

I have more errors:

If a staff write /ji status <player> and the player is offline send a console error, please catch the error and send a custom message.

And other error if the console write /ji status <player>

**Comment by BenjaminZehowlt** [comment]
HitAccuracy bug should be fixed.
The /ji status error will be dealt with in the next major recode.
Closing this as main issue is fixed
