### ISSUE TITLE
Crash auto-banning bug.

### ISSUE THREAD

**Issue by soresdev** [ItemMeta/JI#6]
Ok so I have disabled auto-banning for the Crash check in config, and it is still auto-banning when a player would type //calc. But the thing is it doesn't even ban the player, it broadcasts a message (http://prntscr.com/entom1), that's all it does. I really need this fixed ASAP.

Thanks,
sores

**Comment by BenjaminZehowlt** [comment]
Sorry but this issue is invalid since it doesn't even check if a player used //calc
